const KEY='mis-alquileres-v1';
const sample=[
 {id:'1',name:'Cliente de ejemplo A',dni:'',phone:'Sin registrar',local:'Local de ejemplo 01',rent:850,dueDay:5,notes:'Datos demostrativos',payments:[]},
 {id:'2',name:'Cliente de ejemplo B',dni:'',phone:'Sin registrar',local:'Local de ejemplo 02',rent:1000,dueDay:3,notes:'Datos demostrativos',payments:[{month:currentMonth(),amount:1000,date:todayISO(),method:'Transferencia',receipt:'comprobante-ejemplo.pdf',note:''}]},
 {id:'3',name:'Cliente de ejemplo C',dni:'',phone:'Sin registrar',local:'Local de ejemplo 03',rent:750,dueDay:10,notes:'Datos demostrativos',payments:[]}
];
let tenants=JSON.parse(localStorage.getItem(KEY)||'null')||sample, filter='todos';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function currentMonth(){return new Date().toISOString().slice(0,7)} function todayISO(){return new Date().toISOString().slice(0,10)}
function money(n){return Number(n||0).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2})}
function paid(t){return (t.payments||[]).some(p=>p.month===currentMonth())}
function save(){localStorage.setItem(KEY,JSON.stringify(tenants));render()}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){
 const q=$('#search').value.trim().toLowerCase();
 const rows=tenants.filter(t=>(filter==='todos'||(filter==='pagado')===paid(t))&&[t.name,t.dni,t.phone,t.local].join(' ').toLowerCase().includes(q));
 $('#pendingCount').textContent=tenants.filter(t=>!paid(t)).length; $('#paidCount').textContent=tenants.filter(paid).length; $('#tenantCount').textContent=tenants.length;
 $('#collected').textContent=money(tenants.flatMap(t=>t.payments||[]).filter(p=>p.month===currentMonth()).reduce((s,p)=>s+Number(p.amount),0));
 $('#listTitle').textContent=filter==='pendiente'?'Clientes que faltan pagar':filter==='pagado'?'Clientes que ya pagaron':'Todos los clientes';
 $('#tenantRows').innerHTML=rows.map(t=>`<tr><td class="person"><strong>${esc(t.name)}</strong><small>📞 ${esc(t.phone)}${t.dni?' · DNI '+esc(t.dni):''}</small></td><td>${esc(t.local)}</td><td class="amount">S/ ${money(t.rent)}</td><td>Día ${t.dueDay}</td><td><span class="badge ${paid(t)?'paid':'pending'}">${paid(t)?'✓ Pagado':'⚠ Pendiente'}</span></td><td><div class="row-actions">${!paid(t)?`<button class="pay" onclick="openPayment('${t.id}')">Registrar pago</button>`:''}<button onclick="openDetail('${t.id}')">Ver</button></div></td></tr>`).join('');
 $('#emptyState').hidden=rows.length>0;
}
function setFilter(v){filter=v;$$('.chip').forEach(b=>b.classList.toggle('active',b.dataset.filter===v));render();$('#listTitle').scrollIntoView({behavior:'smooth',block:'start'})}
function toast(m){$('#toast').textContent=m;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function openTenant(t=null){$('#tenantForm').reset();$('#tenantDialogTitle').textContent=t?'Editar cliente':'Registrar nuevo cliente';$('#tenantId').value=t?.id||'';['name','dni','phone','local','rent','dueDay','notes'].forEach(k=>$('#'+k).value=t?.[k]??(k==='dueDay'?5:''));$('#tenantDialog').showModal()}
function openPayment(id){const t=tenants.find(x=>x.id===id);$('#paymentForm').reset();$('#paymentTenantId').value=id;$('#paymentClient').textContent=`${t.name} · ${t.local}`;$('#paymentMonth').value=currentMonth();$('#paymentDate').value=todayISO();$('#amount').value=t.rent;$('#paymentDialog').showModal()}
function openDetail(id){const t=tenants.find(x=>x.id===id), history=[...(t.payments||[])].sort((a,b)=>b.date.localeCompare(a.date));$('#detailContent').innerHTML=`<div class="modal-head"><div class="detail-card"><h2>${esc(t.name)}</h2><p>${esc(t.local)}</p></div><button class="close" onclick="detailDialog.close()">×</button></div><div class="detail-grid"><div><small>Teléfono</small><br><b>${esc(t.phone)}</b></div><div><small>DNI</small><br><b>${esc(t.dni||'No registrado')}</b></div><div><small>Alquiler mensual</small><br><b>S/ ${money(t.rent)}</b></div><div><small>Fecha límite</small><br><b>Día ${t.dueDay}</b></div></div><h3>Historial de pagos</h3>${history.length?`<table class="history"><thead><tr><th>Mes</th><th>Fecha</th><th>Monto</th><th>Comprobante</th></tr></thead><tbody>${history.map(p=>`<tr><td>${esc(p.month)}</td><td>${esc(p.date)}</td><td>S/ ${money(p.amount)}</td><td>${esc(p.receipt||'Sin archivo')}</td></tr>`).join('')}</tbody></table>`:'<p>Aún no tiene pagos registrados.</p>'}<div class="actions"><button class="secondary" onclick="deleteTenant('${t.id}')">Eliminar</button><button class="secondary" onclick="detailDialog.close();openTenant(tenants.find(x=>x.id==='${t.id}'))">Editar</button>${!paid(t)?`<button class="primary" onclick="detailDialog.close();openPayment('${t.id}')">Registrar pago</button>`:''}</div>`;$('#detailDialog').showModal()}
function deleteTenant(id){if(confirm('¿Está seguro de eliminar este cliente y todo su historial?')){tenants=tenants.filter(t=>t.id!==id);save();detailDialog.close();toast('Cliente eliminado')}}
$('#tenantForm').addEventListener('submit',e=>{e.preventDefault();if(!e.target.reportValidity())return;const id=$('#tenantId').value||crypto.randomUUID(),old=tenants.find(t=>t.id===id);const data={id,name:$('#name').value.trim(),dni:$('#dni').value.trim(),phone:$('#phone').value.trim(),local:$('#local').value.trim(),rent:Number($('#rent').value),dueDay:Number($('#dueDay').value),notes:$('#notes').value.trim(),payments:old?.payments||[]};tenants=old?tenants.map(t=>t.id===id?data:t):[data,...tenants];save();$('#tenantDialog').close();toast(old?'Datos actualizados':'Cliente registrado correctamente')});
$('#paymentForm').addEventListener('submit',e=>{e.preventDefault();if(!e.target.reportValidity())return;const t=tenants.find(x=>x.id===$('#paymentTenantId').value);t.payments=t.payments||[];const p={month:$('#paymentMonth').value,amount:Number($('#amount').value),date:$('#paymentDate').value,method:$('#paymentMethod').value,receipt:$('#receipt').files[0]?.name||'',note:$('#paymentNote').value.trim()};const ix=t.payments.findIndex(x=>x.month===p.month);if(ix>=0)t.payments[ix]=p;else t.payments.push(p);save();$('#paymentDialog').close();toast('Pago registrado correctamente')});
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));$('#search').addEventListener('input',render);$('#newTenantBtn').onclick=()=>openTenant();$('#helpBtn').onclick=()=>$('#helpDialog').showModal();
$('#today').textContent=new Intl.DateTimeFormat('es-PE',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date()).replace(/^./,c=>c.toUpperCase());render();
