const KEY='mis-alquileres-v1';
const sample=[
 {id:'1',name:'Cliente de ejemplo A',dni:'',phone:'Sin registrar',local:'Local de ejemplo 01',rent:850,dueDay:5,notes:'Datos demostrativos',payments:[]},
 {id:'2',name:'Cliente de ejemplo B',dni:'',phone:'Sin registrar',local:'Local de ejemplo 02',rent:1000,dueDay:3,notes:'Datos demostrativos',payments:[{month:currentMonth(),amount:1000,date:todayISO(),method:'Transferencia',receipt:'comprobante-ejemplo.pdf',note:''}]},
 {id:'3',name:'Cliente de ejemplo C',dni:'',phone:'Sin registrar',local:'Local de ejemplo 03',rent:750,dueDay:10,notes:'Datos demostrativos',payments:[]}
];
let tenants=JSON.parse(localStorage.getItem(KEY)||'null')||sample, filter='todos';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function currentMonth(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`} function todayISO(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function money(n){return Number(n||0).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2})}
function paid(t){return (t.payments||[]).some(p=>p.month===currentMonth())}
function dueDate(t){const now=new Date(),last=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();return new Date(now.getFullYear(),now.getMonth(),Math.min(Number(t.dueDay)||1,last))}
function paymentStatus(t){if(paid(t))return 'pagado';const today=new Date();today.setHours(0,0,0,0);return today>dueDate(t)?'vencido':'a_tiempo'}
function dueDateText(t){return new Intl.DateTimeFormat('es-PE',{day:'numeric',month:'long',year:'numeric'}).format(dueDate(t))}
function save(){try{localStorage.setItem(KEY,JSON.stringify(tenants))}catch(error){alert('El comprobante es demasiado pesado para esta versión. Seleccione una imagen o PDF de máximo 2 MB.');throw error}render()}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function readFileAsDataURL(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})}
function receiptHtml(p){const url=p.receiptData||p.receiptUrl||'';if(url)return `<a class="receipt-link" href="${esc(url)}" target="_blank" rel="noopener">👁 Abrir comprobante</a><small class="receipt-name">${esc(p.receipt||'Comprobante guardado')}</small>`;return `<span>${esc(p.receipt||'Sin comprobante')}</span><small class="payment-note">${p.receipt?'Vuelva a adjuntar este archivo para poder abrirlo.':'Sin comprobante'}</small>`}
function render(){
 const q=$('#search').value.trim().toLowerCase();
 const rows=tenants.filter(t=>(filter==='todos'||paymentStatus(t)===filter)&&[t.name,t.dni,t.phone,t.local].join(' ').toLowerCase().includes(q));
 $('#overdueCount').textContent=tenants.filter(t=>paymentStatus(t)==='vencido').length; $('#upcomingCount').textContent=tenants.filter(t=>paymentStatus(t)==='a_tiempo').length; $('#paidCount').textContent=tenants.filter(paid).length; $('#tenantCount').textContent=tenants.length;
 $('#collected').textContent=money(tenants.flatMap(t=>t.payments||[]).filter(p=>p.month===currentMonth()).reduce((s,p)=>s+Number(p.amount),0));
 $('#listTitle').textContent=filter==='vencido'?'Clientes vencidos que no pagaron':filter==='a_tiempo'?'Clientes que aún están a tiempo':filter==='pagado'?'Clientes que ya pagaron este mes':'Todos los clientes';
 $('#tenantRows').innerHTML=rows.map(t=>{const status=paymentStatus(t),label=status==='pagado'?'✓ Pagó este mes':status==='vencido'?'⚠ Vencido sin pagar':'🕐 Aún está a tiempo';return `<tr><td class="person"><strong>${esc(t.name)}</strong><small>📞 ${esc(t.phone)}${t.dni?' · DNI '+esc(t.dni):''}</small></td><td>${esc(t.local)}</td><td class="amount">S/ ${money(t.rent)}</td><td><b>${dueDateText(t)}</b></td><td><span class="badge ${status}">${label}</span></td><td><div class="row-actions">${!paid(t)?`<button class="pay" onclick="openPayment('${t.id}')">Registrar pago</button>`:''}<button onclick="openDetail('${t.id}')">Ver</button></div></td></tr>`}).join('');
 $('#emptyState').hidden=rows.length>0;
}
function setFilter(v){filter=v;$$('.chip').forEach(b=>b.classList.toggle('active',b.dataset.filter===v));render();$('#listTitle').scrollIntoView({behavior:'smooth',block:'start'})}
function toast(m){$('#toast').textContent=m;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function openTenant(t=null){$('#tenantForm').reset();$('#tenantDialogTitle').textContent=t?'Editar cliente':'Registrar nuevo cliente';$('#tenantId').value=t?.id||'';['name','dni','phone','local','rent','dueDay','notes'].forEach(k=>$('#'+k).value=t?.[k]??(k==='dueDay'?5:''));$('#tenantDialog').showModal()}
function openPayment(id,month=''){const t=tenants.find(x=>x.id===id),p=(t.payments||[]).find(x=>x.month===month);$('#paymentForm').reset();$('#paymentTenantId').value=id;$('#originalPaymentMonth').value=p?.month||'';$('#paymentDialogTitle').textContent=p?'Editar pago':'Registrar pago';$('#savePaymentBtn').textContent=p?'✓ Guardar cambios':'✓ Confirmar pago';$('#paymentClient').textContent=`${t.name} · ${t.local}`;$('#paymentMonth').value=p?.month||currentMonth();$('#paymentDate').value=p?.date||todayISO();$('#amount').value=p?.amount??t.rent;$('#paymentMethod').value=p?.method||'Efectivo';$('#paymentNote').value=p?.note||'';$('#currentReceipt').textContent=p?.receiptData||p?.receiptUrl?`Comprobante guardado: ${p.receipt}. Seleccione otro solo si desea reemplazarlo.`:p?.receipt?`El archivo anterior (${p.receipt}) no se guardó. Vuelva a seleccionarlo una vez.`:'Puede adjuntar una foto o PDF de máximo 2 MB.';$('#paymentDialog').showModal()}
function openDetail(id){const t=tenants.find(x=>x.id===id), history=[...(t.payments||[])].sort((a,b)=>b.date.localeCompare(a.date));$('#detailContent').innerHTML=`<div class="modal-head"><div class="detail-card"><h2>${esc(t.name)}</h2><p>${esc(t.local)}</p></div><button class="close" onclick="detailDialog.close()">×</button></div><div class="detail-grid"><div><small>Teléfono</small><br><b>${esc(t.phone)}</b></div><div><small>DNI</small><br><b>${esc(t.dni||'No registrado')}</b></div><div><small>Alquiler mensual</small><br><b>S/ ${money(t.rent)}</b></div><div><small>Fecha límite</small><br><b>Día ${t.dueDay}</b></div></div><h3>Historial de pagos</h3>${history.length?`<div class="table-wrap"><table class="history"><thead><tr><th>Mes</th><th>Fecha</th><th>Monto</th><th>Forma</th><th>Comprobante / nota</th><th>Acciones</th></tr></thead><tbody>${history.map(p=>`<tr><td><b>${esc(p.month)}</b></td><td>${esc(p.date)}</td><td>S/ ${money(p.amount)}</td><td>${esc(p.method||'No indicada')}</td><td>${receiptHtml(p)}<small class="payment-note">${esc(p.note||'Sin nota')}</small></td><td><div class="payment-actions"><button class="edit-payment" onclick="detailDialog.close();openPayment('${t.id}','${esc(p.month)}')">Editar pago</button><button class="delete-payment" onclick="deletePayment('${t.id}','${esc(p.month)}')">Eliminar pago</button></div></td></tr>`).join('')}</tbody></table></div>`:'<p>Aún no tiene pagos registrados.</p>'}<div class="actions"><button class="secondary" onclick="deleteTenant('${t.id}')">Eliminar cliente</button><button class="secondary" onclick="detailDialog.close();openTenant(tenants.find(x=>x.id==='${t.id}'))">Editar cliente</button>${!paid(t)?`<button class="primary" onclick="detailDialog.close();openPayment('${t.id}')">Registrar pago</button>`:''}</div>`;$('#detailDialog').showModal()}
function deletePayment(id,month){const t=tenants.find(x=>x.id===id),p=(t?.payments||[]).find(x=>x.month===month);if(!t||!p)return;const message=`¿Eliminar este pago?\n\nCliente: ${t.name}\nMes: ${p.month}\nMonto: S/ ${money(p.amount)}\n\nEl cliente volverá a figurar como pendiente si corresponde.`;if(confirm(message)){t.payments=t.payments.filter(x=>x.month!==month);save();detailDialog.close();toast('Pago eliminado. El estado fue actualizado.');setTimeout(()=>openDetail(id),150)}}
function deleteTenant(id){if(confirm('¿Está seguro de eliminar este cliente y todo su historial?')){tenants=tenants.filter(t=>t.id!==id);save();detailDialog.close();toast('Cliente eliminado')}}
$('#tenantForm').addEventListener('submit',e=>{e.preventDefault();if(!e.target.reportValidity())return;const id=$('#tenantId').value||crypto.randomUUID(),old=tenants.find(t=>t.id===id);const data={id,name:$('#name').value.trim(),dni:$('#dni').value.trim(),phone:$('#phone').value.trim(),local:$('#local').value.trim(),rent:Number($('#rent').value),dueDay:Number($('#dueDay').value),notes:$('#notes').value.trim(),payments:old?.payments||[]};tenants=old?tenants.map(t=>t.id===id?data:t):[data,...tenants];save();$('#tenantDialog').close();toast(old?'Datos actualizados':'Cliente registrado correctamente')});
$('#paymentForm').addEventListener('submit',async e=>{e.preventDefault();if(!e.target.reportValidity())return;const t=tenants.find(x=>x.id===$('#paymentTenantId').value),original=$('#originalPaymentMonth').value,old=(t.payments||[]).find(x=>x.month===original),file=$('#receipt').files[0];if(file&&file.size>2*1024*1024){alert('El comprobante debe pesar como máximo 2 MB. Puede comprimirlo o tomar una foto más liviana.');return}const receiptData=file?await readFileAsDataURL(file):old?.receiptData||old?.receiptUrl||'';t.payments=(t.payments||[]).filter(x=>!original||x.month!==original);const p={month:$('#paymentMonth').value,amount:Number($('#amount').value),date:$('#paymentDate').value,method:$('#paymentMethod').value,receipt:file?.name||old?.receipt||'',receiptData,receiptType:file?.type||old?.receiptType||'',note:$('#paymentNote').value.trim()};const ix=t.payments.findIndex(x=>x.month===p.month);if(ix>=0)t.payments[ix]=p;else t.payments.push(p);save();$('#paymentDialog').close();toast(original?'Pago actualizado correctamente':'Pago registrado correctamente')});
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));$('#search').addEventListener('input',render);$('#newTenantBtn').onclick=()=>openTenant();$('#helpBtn').onclick=()=>$('#helpDialog').showModal();
const dueDayInput=$('#dueDay'),dueDayLabel=dueDayInput.parentElement;dueDayLabel.childNodes[0].textContent='¿Qué día de cada mes debe pagar? *';dueDayInput.placeholder='Ejemplo: 5';const dueDayHelp=document.createElement('small');dueDayHelp.textContent='Si paga todos los meses el día 5, escriba solamente 5.';dueDayInput.after(dueDayHelp);
$('#today').textContent=new Intl.DateTimeFormat('es-PE',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date()).replace(/^./,c=>c.toUpperCase());render();
